language: python
python:
  - "2.7"
env:
  - DJANGO=1.6.1
install:
  - pip install -r requirements.txt
before_script:
  - "cp $TRAVIS_BUILD_DIR/frontcast/local_settings.sample.py $TRAVIS_BUILD_DIR/frontcast/local_settings.py"
  - "mkdir -p $TRAVIS_BUILD_DIR/logs"
script:
  - python manage.py test
